type: Generator
stop_generator_when_sequence_finishes: ALL
max_runtime_ms: 1000000
generator_rate_type: FIXED
generator_rate_config: emitRate 1000
seed: 1
generator_schema: |
  SEQUENCE UINT64  0 10 1
  SEQUENCE UINT32  0  9 1
  SEQUENCE UINT16  0  8 1
  SEQUENCE UINT8   0  7 1
  SEQUENCE INT64   0  6 1
  SEQUENCE INT32   0  5 1
  SEQUENCE INT16   0  4 1
  SEQUENCE INT8    0  3 1
  SEQUENCE FLOAT64 0  2 1
  SEQUENCE FLOAT32 0  1 1
