logical: PLACEHOLDER
parserConfig:
  type: CSV
  fieldDelimiter: ','
sourceConfig:
  type: TCP
  numberOfBuffersInSourceLocalBufferPool: 16
  socketDomain: AF_INET
  socketType: SOCK_STREAM
  socketPort: PLACEHOLDER
  socketHost: PLACEHOLDER
  socketBufferSize: 2
  flushIntervalMS: 100
  connectTimeoutSeconds: 60
  filePath: PLACEHOLDER
