# ~~~ Configurations for the NES E2E Selection Benchmark ~~~

#Location of query set
# For each query set we will run the experiments
querySetLocation: '/home/ankit-ldap/tmp/nes/benchmark/src/Micro-Benchmarks/Query-Merger/QueryLoad'
#querySetLocation: '/home/ankit/dima/nes/benchmark/src/Micro-Benchmarks/Query-Merger/QueryLoad'

# Parameter that are changed per run with comma separated list
#queryMergerRule: Z3SignatureBasedPartialQueryMergerBottomUpRule,SyntaxBasedPartialQueryMergerRule,ImprovedStringSignatureBasedPartialQueryMergerRule,Z3SignatureBasedPartialQueryMergerRule
  #,ImprovedStringSignatureBasedPartialQueryMergerRule,Z3SignatureBasedPartialQueryMergerRule
  #,HybridCompleteQueryMergerRule,SyntaxBasedCompleteQueryMergerRule,ImprovedStringSignatureBasedCompleteQueryMergerRule
  #,SyntaxBasedCompleteQueryMergerRule
# Z3SignatureBasedCompleteQueryMergerRule,ImprovedStringSignatureBasedCompleteQueryMergerRule,SyntaxBasedCompleteQueryMergerRule
#,HybridCompleteQueryMergerRule,ImprovedStringSignatureBasedCompleteQueryMergerRule
#queryMergerRule: Z3SignatureBasedCompleteQueryMergerRule,SyntaxBasedCompleteQueryMergerRule,HybridCompleteQueryMergerRule,DefaultQueryMergerRule,HashSignatureBasedCompleteQueryMergerRule,ImprovedStringSignatureBasedCompleteQueryMergerRule
queryMergerRule: Z3SignatureBasedPartialQueryMergerRule,SyntaxBasedPartialQueryMergerRule,DefaultQueryMergerRule,StringSignatureBasedPartialQueryMergerRule,ImprovedStringSignatureBasedPartialQueryMergerRule,Z3SignatureBasedPartialQueryMergerBottomUpRule
noOfPhysicalSources: 1,1,1,1,1,1
#  ,1,1,1,1
batchSize: 1,1,1,1,1,1
#  ,1,1,1,1

#benchmark internal parameter
logLevel: LOG_ERROR
numberOfDistinctSources: 10
startupSleepIntervalInSeconds: 3
numberOfMeasurementsToCollect: 3
