workers:
  - host: "sink-node:8080"
    connection: "sink-node:9090"
    capacity: 10000
  - host: "source-node:8080"
    connection: "source-node:9090"
    capacity: 4
    downstream:
      - "sink-node:8080"

allow_source_placement:
  - "source-node:8080"

allow_sink_placement:
  - "sink-node:8080"
  - "source-node:8080"
