# ~~~ Configurations for the NES Worker ~~~

# ~~ IPs and Ports ~~
# Set worker IP
localWorkerIp: 127.0.0.1

# Set IP address of NES Coordinator to which the NES Worker should connect
coordinatorIp: 127.0.0.1

# Set RPC Server port of NES Coordinator to which the NES Worker should connect
# Needs to be the same as rpcPort in Coordinator
coordinatorPort: 4000

# Set RPC server port of NES Worker
rpcPort: 3000

# Set the data port of the NES Worker
dataPort: 3001

# Set number of computing slots in NES Worker
numberOfSlots: 65535

# Set the number of worker threads
numWorkerThreads: 1

# Number buffers in global buffer pool
numberOfBuffersInGlobalBufferManager: 1024

# Number buffers in task local buffer pool
numberOfBuffersPerWorker: 128

# Number buffers in source local buffer pool
numberOfBuffersInSourceLocalBufferPool: 64

# Size of buffer to pass data through the system
bufferSizeInBytes: 4096

# Set parentId of NES Worker node
parentId: -1

# The log level (LOG_NONE, LOG_WARNING, LOG_DEBUG, LOG_INFO, LOG_TRACE)
logLevel: LOG_DEBUG
