worker:
  throughputListenerTimeInterval: 1000
  numberOfBuffersInGlobalBufferManager: 2000000
  numberOfBuffersPerWorker: 1000
  numberOfBuffersInSourceLocalPools: 1000
  bufferSizeInBytes: 4096
  queryOptimizer:
    executionMode: COMPILER
    pipelinesTxtFilePath: ""
    pageSize: 4096
    sliceStoreType: DEFAULT
    lowerMemoryBound: 0
    upperMemoryBound: 0
    maxNumWatermarkGaps: 0
    maxNumSequenceNumbers: 0
    minReadStateSize: 0
    minWriteStateSize: 0
    fileOperationTimeDelta: 0
    fileLayout: NO_SEPARATION
    withPrediction: true
    watermarkPredictorType: KALMAN
    fileDescriptorGenerationRate: 100
    fileDescriptorBufferSize: 4096
    numberOfBuffersPerWorker: 256
    fileBackedWorkingDir: ""

  queryEngine:
    numberOfWorkerThreads: 1
    taskQueueSize: 1000
#    statisticsDir: TBA
